@include test('sass-errors-try-catch') {
  // `sass-errors-try-catch` require to be declared in the same scope as handler function
  @import '../../../scss/sass-errors/api/sass-errors-try-catch';

  $_: sass-errors-init();

  $expected_exception: (
    message: 'ERROR',
    error: 'ERROR',
    type: 'TYPE',
    datas: ()
  );

  @function -test-return-value() {
    @return 'VALUE';
  }

  @function -test-throw-exception() {
    @return sass-errors-throw('ERROR', 'TYPE');
  }

  @function -test-exception-handler($e) {
    $-test-function-exception: $e;
    @return null;
  }

  $-test-function-exception: null;
  $ret: sass-errors-try-catch(-test-return-value(), -test-exception-handler, ());
  @include assert-equal($ret, 'VALUE',
      'If a value is returned, should return the value of the try function.');
  @include assert-equal(sass-errors-is-exception(), false,
      'If a value is returned, should do not throw Exceptions.');
  @include assert-equal($-test-function-exception, null,
      'If a value is returned, should do not call the catch function.');

  $-test-function-exception: null;
  $ret: sass-errors-try-catch(-test-throw-exception(), '-test-exception-handler', ());
  @include assert-equal($ret, false,
      'If an Exception has been thrown, should return `false`.');
  @include assert-equal(sass-errors-is-exception(), false,
      'If an Exception has been thrown, should catch the Exception.');
  @include assert-equal($-test-function-exception, $expected_exception,
      'If an Exception has been thrown, should pass the Exception to the catch function.');

}
